name: Release Please

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    uses: novasafe-org/novasafe-deployment/.github/workflows/release-please.yml@master
    secrets: inherit
